// <auto-generated />
using System;
using BMW_GarageWebApi.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMW_GarageWebApi.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240907112450_createDataBaseBMW")]
    partial class createDataBaseBMW
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BMW_GarageWebApi.Domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfHiring")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(1998, 6, 16),
                            DateOfHiring = new DateOnly(2021, 2, 11),
                            Email = "sergizezeria147@gmail.com",
                            FullName = "Жежеря Сергій Вікторович",
                            Gender = 0,
                            ImageUrl = "",
                            Notes = "Досконале володіння діагностичними інструментами та обладнанням для виявлення та вирішення широкого кола автомобільних проблем",
                            PhoneNumber = "+48 456 346 641",
                            Position = "Автомеханік"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateOnly(1991, 5, 15),
                            DateOfHiring = new DateOnly(2021, 2, 11),
                            Email = "rub4iksergo@gmail.com",
                            FullName = "Рубаков Сергій Єрвандович",
                            Gender = 0,
                            ImageUrl = "",
                            Notes = "Відмінні комунікативні навички, надання чітких пояснень щодо ремонту та технічного обслуговування клієнтам",
                            PhoneNumber = "+48 116 287 743",
                            Position = "Автомеханік"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateOnly(1998, 6, 11),
                            DateOfHiring = new DateOnly(2021, 2, 12),
                            Email = "gladkoua@gmail.com",
                            FullName = "Гладкий Ігор Сергійович",
                            Gender = 0,
                            ImageUrl = "",
                            Notes = "здатність швидко й ефективно усувати проблеми, забезпечуючи мінімальний час простою для клієнтів",
                            PhoneNumber = "+48 688 966 121",
                            Position = "Автомеханік"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
